_wandb:
    value:
        cli_version: 0.22.0
        e:
            5l9ymacp0nqrq0i4dozw2ldfpmhzyvko:
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1022782410752"
                        used: "739982774272"
                email: bizon.mimi@gmail.com
                executable: C:\Users\bizon\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 402ab8132f2dc4c45a7789454ad0449be79df149
                    remote: https://github.com/JozefBizon/AB_zneus_01.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-715a99be-6dac-763a-f39e-e2722a57ecff
                host: Bizon
                memory:
                    total: "16782184448"
                os: Windows-11-10.0.26100-SP0
                program: project1-jvsc-b2baac58-8689-4fe7-bd02-373f61330df45568aae8-df49-4273-8870-207562db42ea.ipynb
                python: CPython 3.13.0
                root: C:\Users\bizon\Desktop\skola\5.semester\ZNEUS\projekt1\AB_zneus_01
                startedAt: "2025-11-08T13:02:27.336576Z"
                writerId: 5l9ymacp0nqrq0i4dozw2ldfpmhzyvko
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 16
            "4": 3.13.0
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
architecture:
    value: SimpleNN
class_weight_ratio:
    value: 5.131747483989021
epochs:
    value: 5000
hidden_layers:
    value:
        - 16
        - 8
input_features:
    value: 8
learning_rate:
    value: 0.001
loss_function:
    value: BCELoss
negative_samples:
    value: 5609
optimizer:
    value: Adam
positive_samples:
    value: 1093
training_samples:
    value: 6702
